version: '2'
services:
  web:
    build: .
    image: pdxdiver/django-web:latest
    command: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
